db_en = [
    "that", "with", "from", "this", "they", "will", "would", "about", "their", "there",
    "what", "which", "when", "make", "time", "just", "know", "take", "people", "into",
    "year", "your", "good", "some", "could", "them", "other", "than", "then", "look",
    "only", "come", "over", "think", "also", "back", "after", "work", "first", "well",
    "even", "want", "because", "these", "give", "most", "thing", "such", "tell", "many",
    "very", "find", "here", "being", "before", "between", "must", "where", "right",
    "through", "around", "today", "different", "without", "should", "place", "every",
    "under", "small", "found", "still", "under", "part", "home", "during", "another",
    "large", "learn", "always", "until", "night", "along", "follow", "problem", "begin",
    "might", "water", "often", "together", "family", "direct", "leave", "measure", "door",
    "product", "black", "short", "digit", "class", "wind", "question", "happen", "complete",
    "ship", "area", "half", "rock", "order", "fire", "south", "problem", "piece", "told",
    "knew", "pass", "since", "top", "whole", "king", "space", "heard", "best", "hour",
    "better", "true", "during", "hundred", "remember", "step", "early", "hold", "west",
    "ground", "interest", "reach", "fast", "verb", "sing", "listen", "six", "table",
    "travel", "less", "morning", "ten", "simple", "several", "vowel", "toward", "war",
    "lay", "against", "pattern", "slow", "center", "love", "person", "money", "serve",
    "appear", "road", "map", "rain", "rule", "govern", "pull", "cold", "notice", "voice",
    "unit", "power", "town", "fine", "certain", "fly", "fall", "lead", "cry", "dark",
    "machine", "note", "wait", "plan", "figure", "star", "box", "noun", "field", "rest",
    "correct", "able", "pound", "done", "beauty", "drive", "stood", "contain", "front",
    "teach", "week", "final", "gave", "green", "quick", "develop", "ocean", "warm",
    "free", "minute", "strong", "special", "mind", "behind", "clear", "tail", "produce",
    "fact", "street", "inch", "multiply", "nothing", "course", "stay", "wheel", "full",
    "force", "blue", "object", "decide", "surface", "deep", "moon", "island", "foot",
    "system", "busy", "test", "record", "boat", "common", "gold", "possible", "plane",
    "stead", "dry", "wonder", "laugh", "thousand", "ago", "ran", "check", "game", "shape",
    "equate", "hot", "miss", "brought", "heat", "snow", "tire", "bring", "yes", "distant",
    "fill", "east", "paint", "language", "among", "grand", "ball", "yet", "wave", "drop",
    "heart", "am", "present", "heavy", "dance", "engine", "position", "arm", "wide",
    "sail", "material", "size", "vary", "settle", "speak", "weight", "general", "ice",
    "matter", "circle", "pair", "include", "divide", "syllable", "felt", "perhaps", "pick",
    "sudden", "count", "square", "reason", "length", "represent", "art", "subject", "region",
    "energy", "hunt", "probable", "bed", "brother", "egg", "ride", "cell", "believe",
    "fraction", "forest", "sit", "race", "window", "store", "summer", "train", "sleep",
    "prove", "lone", "leg", "exercise", "wall", "catch", "mount", "wish", "sky", "board",
    "joy", "winter", "sat", "written", "wild", "instrument", "kept", "glass", "grass",
    "cow", "job", "edge", "sign", "visit", "past", "soft", "fun", "bright", "gas",
    "weather", "month", "million", "bear", "finish", "happy", "hope", "flower", "clothe",
    "strange", "gone", "jump", "baby", "eight", "village", "meet", "root", "buy", "raise",
    "solve", "metal", "whether", "push", "seven", "paragraph", "third", "shall", "held",
    "hair", "describe", "cook", "floor", "either", "result", "burn", "hill", "safe", "cat",
    "century", "consider", "type", "law", "bit", "coast", "copy", "phrase", "silent",
    "tall", "sand", "soil", "roll", "temperature", "finger", "industry", "value", "fight",
    "lie", "beat", "excite", "natural", "view", "sense", "ear", "else", "quite", "broke",
    "case", "middle", "kill", "son", "lake", "moment", "scale", "loud", "spring", "observe",
    "child", "straight", "consonant", "nation", "dictionary", "milk", "speed", "method",
    "organ", "pay", "age", "section", "dress", "cloud", "surprise", "quiet", "stone",
    "tiny", "climb", "cool", "design", "poor", "lot", "experiment", "bottom", "key",
    "iron", "single", "stick", "flat", "twenty", "skin", "smile", "crease", "hole", "trade",
    "melody", "trip", "office", "receive", "row", "mouth", "exact", "symbol", "die", "least",
    "trouble", "shout", "except", "wrote", "seed", "tone", "join", "suggest", "clean",
    "break", "lady", "yard", "rise", "bad", "blow", "oil", "blood", "touch", "grew",
    "cent", "mix", "team", "wire", "cost", "lost", "brown", "wear", "garden", "equal",
    "sent", "choose", "fell", "fit", "flow", "fair", "bank", "collect", "save", "control",
    "decimal", "gentle", "woman", "captain", "practice", "separate", "difficult", "doctor",
    "please", "protect", "noon", "crop", "modern", "element", "hit", "student", "corner",
    "party", "supply", "whose", "locate", "ring", "character", "insect", "caught", "period",
    "indicate", "radio", "spoke", "atom", "human", "history", "effect", "electric", "expect",
    "bone", "rail", "imagine", "provide", "agree", "thus", "gentle", "woman", "captain",
    "guess", "necessary", "sharp", "wing", "create", "neighbor", "wash", "bat", "rather",
    "crowd", "corn", "compare", "poem", "string", "bell", "depend", "meat", "rub", "tube",
    "famous", "dollar", "stream", "fear", "sight", "thin", "triangle", "planet", "hurry",
    "chief", "colony", "clock", "mine", "tie", "enter", "major", "fresh", "search", "send",
    "yellow", "gun", "allow", "print", "dead", "spot", "desert", "suit", "current", "lift",
    "rose", "continue", "block", "chart", "hat", "sell"
]
